Last login: Mon Jun 22 20:28:20 on ttys000
(base) lokesh@lokeshs-Laptop ~ % cd /Users/lokesh/Desktop/hackathon
(base) lokesh@lokeshs-Laptop hackathon % ls -a
.			.streamlit		app.py
..			.streamlit:secrets.toml	secrets.toml
(base) lokesh@lokeshs-Laptop hackathon % rm ".streamlit:secrets.toml"
(base) lokesh@lokeshs-Laptop hackathon % mkdir -p .streamlit
(base) lokesh@lokeshs-Laptop hackathon % nano .streamlit/secrets.toml
















  UW PICO 5.09                                                                             File: .streamlit/secrets.toml                                                                             Modified  

OPENAI_API_KEY="sk-your_real_api_key"





















































^G Get Help                       ^O WriteOut                       ^R Read File                      ^Y Prev Pg                        ^K Cut Text                       ^C Cur Pos                        
^X Exit                           ^J Justify                        ^W Where is                       ^V Next Pg                        ^U UnCut Text                     ^T To Spell                       
